services:
  zimacube-fan-controller:
    build:
      context: .

    container_name: zimacube-fan-controller
    restart: unless-stopped
    network_mode: none

    devices:
      - /dev/i2c-0:/dev/i2c-0:rwm

    volumes:
      - /var/local/emhttp/var.ini:/var/local/emhttp/var.ini:ro
      - /var/local/emhttp/disks.ini:/var/local/emhttp/disks.ini:ro

    environment:
      I2C_BUS: "0"
      I2C_ADDRESS: "0x69"

      NORMAL_PERCENT: "90"
      HIGH_PERCENT: "100"

      HIGH_TEMP: "47"
      LOW_TEMP: "44"

      CHECK_INTERVAL: "15"
      I2C_RETRIES: "3"

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    healthcheck:
      test:
        - CMD
        - /usr/local/bin/healthcheck.sh
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

    tmpfs:
      - /run/fan-controller:size=1m,nosuid,nodev,noexec