services:
  zimacube-fan-controller:
    build: .

    container_name: zimacube-fan-controller

    restart: unless-stopped

    network_mode: none

    devices:
      - /dev/i2c-0:/dev/i2c-0

    environment:
      FAN_PERCENT: "90"
      I2C_BUS: "0"
      I2C_ADDRESS: "0x69"

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    cap_add:
      - SYS_RAWIO